# Generated by Django 5.2.1 on 2025-05-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_point', models.CharField(blank=True, max_length=100, null=True)),
                ('end_point', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=6)),
                ('elevation_gain', models.DecimalField(decimal_places=2, help_text='Elevation gain in meters', max_digits=6)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('trail_type', models.CharField(choices=[('Loop', 'Loop'), ('Out & Back', 'Out & Back'), ('Point-to-Point', 'Point-to-Point')], max_length=20)),
                ('estimated_time', models.DecimalField(decimal_places=2, help_text='Estimated time in hours', max_digits=4)),
                ('trail_conditions', models.TextField(blank=True, null=True)),
                ('accessibility', models.TextField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='trail_photos/')),
                ('user_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
