# Generated by Django 5.2.1 on 2025-05-18 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailQuest', '0002_alter_trail_latitude_alter_trail_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='admin_comments',
            field=models.TextField(blank=True, help_text='Administrator approval or rejection comments', null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trail',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
