# Generated by Django 5.2.1 on 2025-05-19 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailQuest', '0003_trail_admin_comments_trail_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('poor', '1 - Poor'), ('fair', '2 - Fair'), ('good', '3 - Good'), ('very good', '4 - Very Good'), ('excellent', '5 - Excellent')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trailQuest.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
