# Generated by Django 5.2.1 on 2025-05-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailQuest', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=18),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.DecimalField(decimal_places=2, help_text='Elevation gain in meters', max_digits=18),
        ),
        migrations.AlterField(
            model_name='trail',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, help_text='Estimated time in hours', max_digits=18),
        ),
        migrations.AlterField(
            model_name='trail',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
